### ISSUE TITLE
Great work! Can I add extension deployment code

### ISSUE THREAD

**Issue by cookiejest** [mountaindude/butler#16]
Hey this is really impressive, thanks for sharing this. I have some functionality that is used for deploying Qlik Sense extensions through the API to Qlik Sense Enterprise via push to GIT repository (where multiple branches of the same visualisation will then exist in Qlik Sense for development and testing. Would you mind if I try adding this into butler also?

**Comment by mountaindude** [comment]
I am myself adding all new features as stand-alone micro-services, that themselves become part of the larger Butler family. 

The first Butler project grew to become larger and larger, to the point I realised it would eventually be hard to understand for newcomers, and hard to maintain for those so inclined. 
For example, "Butler SOS" is a stand-alone project, as is the "App duplicator". 
The nice part about writing them all in Node is that it's super convenient to run them all from a process monitor such as PM2. 

Thus, you could fork the main Butler project and add the code there, or create a new microservice doing what you suggest. You can of course be inspired by and borrow code from the other Butler microservices as needed

I would suggest the second option, due to better scalability. Would love to see you code in action - so if I can help I will of course do so!

**Comment by cookiejest** [comment]
I will look at using one of the micro services you have created as a base for a 'Qlik Deploy' nodejs service. Again great work! Watch this space.

**Comment by mountaindude** [comment]
Great - look forward to seeing it in action!
